name: Mobile System Automation CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted 
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Python Dependencies
      run: pip install -r requirements.txt

    - name: Run Tests on Physical Hardware (HIL)
      run: pytest -m test_vitals.py -v -s